# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code. this is a super long line this is a super long linethis is a super long linethis is a super long linethis is a super long linethis is a super long linethis is a super long linethis is a super long linethis is a super long linethis is a super long line
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr:
  branches:
    include:
    - main
    - releases/*
    exclude:
    - releases/old*
  drafts: false

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
